apiVersion: v1
kind: Node
metadata:
  name: bigip1
  annotations:
    #Replace IP with self IP for your deployment
    flannel.alpha.coreos.com/public-ip: "${bigip-internal}"
    #Replace MAC with your BIG-IP Flannel VXLAN Tunnel MAC
    flannel.alpha.coreos.com/backend-data: '{"VtepMAC":"${bigip-tunnel-mac}"}'
    flannel.alpha.coreos.com/backend-type: "vxlan"
    flannel.alpha.coreos.com/kube-subnet-manager: "true"
spec:
  #Replace Subnet with your BIG-IP Flannel Subnet
  podCIDR: "${podsubnet}"